spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "3.0"

accounts:
  message: "Welcome to accounts related local APIs "
  contactDetails:
    name: "John Doe - prod"
    email: "john@pblgllgs.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345